# Generated by Django 2.0.4 on 2018-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(default='contact@neuro-studio.com', max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
