# Generated by Django 2.0.7 on 2018-07-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PressItemImage',
            fields=[
                ('pressitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='press.PressItem')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('press.pressitem',),
        ),
        migrations.CreateModel(
            name='PressItemQuote',
            fields=[
                ('pressitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='press.PressItem')),
                ('quote', models.TextField()),
                ('publication', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('press.pressitem',),
        ),
        migrations.AddField(
            model_name='pressitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_press.pressitem_set+', to='contenttypes.ContentType'),
        ),
    ]
