# Generated by Django 2.0.7 on 2018-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20180716_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('item_type', models.IntegerField(choices=[(1, 'quote'), (2, 'image')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('quote', models.TextField(blank=True)),
                ('publication', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
