# Generated by Django 2.0.6 on 2018-07-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_pressitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressitem',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'quote'), (1, 'image')], default=0),
        ),
    ]
