# Generated by Django 2.0.6 on 2018-06-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('clothing_type', models.IntegerField(choices=[(1, 'dress'), (2, 'accessory'), (3, 'jacket'), (4, 'pants'), (5, 'top'), (6, 'shoes')], default=0)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('materials', models.TextField(blank=True, max_length=500)),
                ('main_image', models.ImageField(upload_to='photos')),
                ('thumbnail', models.ImageField(upload_to='photos')),
                ('detail_1', models.ImageField(upload_to='photos')),
                ('detail_2', models.ImageField(upload_to='photos')),
                ('detail_3', models.ImageField(upload_to='photos')),
                ('detail_4', models.ImageField(upload_to='photos')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
