# Generated by Django 2.0.6 on 2018-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page_type', models.IntegerField(choices=[(1, 'text'), (2, 'slider')], default=0)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
